"""
ComfyUI WhisperX Pro - Accurate Audio Transcription and Alignment Nodes
"""

from .whisperx_alignment_node import NODE_CLASS_MAPPINGS as ALIGNMENT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALIGNMENT_NODE_DISPLAY_NAME_MAPPINGS
from .whisperx_srt_node import NODE_CLASS_MAPPINGS as SRT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SRT_NODE_DISPLAY_NAME_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **ALIGNMENT_NODE_CLASS_MAPPINGS,
    **SRT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **ALIGNMENT_NODE_DISPLAY_NAME_MAPPINGS,
    **SRT_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']